### ISSUE TITLE
One of two TV not turning on

### ISSUE THREAD

**Issue by RichW02** [o-lukas/homebridge-smartthings-tv#32]
Please excuse my errors in this request, I'm new at this, well and old new, it been quite a few years since I did and network configuring...

I have installed the home bridge-smartthing-tv plugin and it installed ok. I added two Samsung TV's of different age.  The IOS Smartthings app on my phone works flawlessly.  I added them to HomeKit, the older of the two works well turns off/on/change input etc.  The second a QA65Q800TAWXXY model, can turn off and changes inputs but will NOT turn ON, but will turn off.

Is there something I've missed, like a WOL or some other permission ?  I've deleted and re-added without any change.    The Samsung access key seems correct, no errors I can see.

Is there a configurable delay between commands anywhere? 

I have not seen any popup on the TV to authorise, apart from bluetooth direct from my phone. 

There didn't deem to be anything in the log file except for an unsupported Air Purifier, also in SmartThings.  There we a few input errors, because I didn't change the config file much from the example, but I didn't change anything as one worked and the other didn't.

Logs: Attached.

config-.json attached.

[config-json.txt](https://github.com/o-lukas/homebridge-smartthings-tv/files/10989024/config-json.txt)

[LogFile-RW .txt](https://github.com/o-lukas/homebridge-smartthings-tv/files/10989034/LogFile-RW.txt)

**Comment by o-lukas** [comment]
I'm not really sure what is happening but your config looks good. There should not be any permissions issues and even if there was any permission issue your other TV should not work too.

WOL will be used as soon as there is a MAC address set in your device mappings. So because you set one it should be used.

Could you please try to enable Debug log level and post your log file again. So I can have a closer look at what is happening. Currently I can not reproduce the problem as I only have one TV available and not your specific model. To enable Debug log level simply go to Homebridge settings in config UI and enable Homebridge Debug Mode in startup options.

**Comment by RichW02** [comment]
I've attached a full copy of the log files after a Pi reboot and then a home bridge restart.  Other junk is still there...........

I can see the WOL in the log. The TV "Living TV" is the problem one, I have to clean up the names as they got mixed up some how.  At the end of the log I have toggled the ON from HomeBridge a few times, then turned it on from the SmartLife app, then turned it off.  It seems like Homebridge sends the ON but does not get a reply so turn the button off again.  When Smartlife turns it on homebridge see the state go on, correctly, from then it can then turn it off.

Also, how do i remove the inputs with error (compatibility i think)

[homebridge.log-5.txt](https://github.com/o-lukas/homebridge-smartthings-tv/files/11001385/homebridge.log-5.txt)

**Comment by o-lukas** [comment]
Thanks for the quick response!

I have created a [new release](https://github.com/o-lukas/homebridge-smartthings-tv/releases/tag/v1.0.4) where the success/failure of the wake-on-lan functionality will be logged. Please try to use this release and check if the log says the wake-on-lan failed. If this continues to happen please disable wake-on-lan functionality by removing the mac address of the TV from the device mapping and try again.

The wake-on-lan functionality was just a bugfix for me because my TV did not turn on using the SmartThings API. Maybe SmartThings API works for your TV.

**Comment by RichW02** [comment]
Thanks for all the help, attached is a log file, as requested.  

Look from 1:54 pm, that is where I selected the on from home bridge, saw the indication come on for a while then go off, TV nothing.  Turned the TV on from Smartlife, then the status in homebriddge starting working .

Regards, Richard.....

[homebridge.log-7.txt](https://github.com/o-lukas/homebridge-smartthings-tv/files/11010223/homebridge.log-7.txt)

**Comment by o-lukas** [comment]
It seems the wake-on-lan command was sent successfully but the TV did somehow not react to it. Have you tried sending a wake-on-lan command from outside the plugin so that we can be sure the TV is capable of handling it? Is the TV connected over wifi - sometimes wake-on-lan does not work very well over wifi?

But when turning on the TV using SmartThings is working for you, you could try to remove the mac address from the device mappings configuration entry. As I said you should only need the wake-on-lan functionality if the SmartThings API is not working for you. As it seems to work for your TV you can disable it (by removing the mac address) and you should be fine.

**Comment by RichW02** [comment]
Thanks heaps for your time, I have attached another log file after deleting the mac address via the UI config.  Then restarted.  When accessory of the TV returned the inputs were incorrect.  
At about 13:10pm I toggled the living_tv on form the HomeBridge accessory display.  The TV came on (Hooray) however the status feedback soon went off, the TV remained ON.  I toggled the state in Smartthings app, the TV indication came on again everywhere.  
At about 13:16 the TV status went off again even though the TV remained on.  The status went off again about 13:16, set on again. 
I restarted the bridge again, the status was off and a start from HK change the status and went off again ~13:35 and the inputs now show the correct input names and changed from home bridge.

My observations:

1. Living TV can now be turned ***ON*** from the HB or HK or SmartThings,
2. 2 restarts required to get inputs to show correctly for Living TV in HB.
3. Status indication (feedback)initially correct but fail after 2 to 3 minutes.
4. 2nd TV still working correctly.  BTW I already new that the second TV WOL will only functions with a hardwired ethernet connection, it will not work with wifi.
5. The second accessory for the TV Mute/Vol ? only seems to mute and will not unmute and % display always 0%
6. The log file shows a lot of failed PINGS, with only 1 attempt each. (100% packet loss)
7. There seems to be a lot of pings with the same (seconds) time stamp, this seems like a high number of commands per second, I was under the impression a shot delay was required between PINGS, >200ms.?

Thanks for your help much appreciated, I'll add a donation when I can find out how..:)
regards,
Richard.....

[RJW-log-3.txt](https://github.com/o-lukas/homebridge-smartthings-tv/files/11014168/RJW-log-3.txt)

**Comment by RichW02** [comment]
Oops thanks for reopening. 
late update, I tried WOL and the tv turned on every time even after hours off. 
I tried PING, it seems strange, sometimes it responded, especially when I pinged the whole subnet, ( slow rate) but usually failed when I pinged on a regular time.  I don’t understand it’s behavior, so I try resetting the TV tomorrow,
 I’m a little busy, so I may not get time early, I’ve got a few things to do before my grandson arrives from the UK Thursday.… 
Seems like it may be my end, let me know you donation link and I’ll send a little something.

**Comment by RichW02** [comment]
I managed to do some pinging and noticed:


- I started pinging the TV at about 800ms constant rate.
- No response from TV at first.
- De-Powering the TV and back on again, pinging was successful at about 5ms > 15ms
- Watched it start a constant **alive** results for a few minutes 0% lost.
- I turned the TV off.
- Then restarted the bridge.
- When HB got to the point of adding the inputs, the pinging **stopped** responding completely.
- I turned the TV back on and pinging response restarted with constant **alive**.
- I tried this a few times and with the TV off (in standby) a restart of the bridge would crash the TV, no response.
- The TV when turned back on, it started responding again, but the TV screen started
[homebridge.log-9.txt](https://github.com/o-lukas/homebridge-smartthings-tv/files/11035161/homebridge.log-9.txt)
 at the cold start screen, not the warm start. Also the TV changes to the inputs the plugin adds, E.G Apple TV+, Spotify are put on the screen one after the other until it got though all the inputs (that I don't want).
- The log file did not ever show an alive status even though I was getting a constant reply to my continuous ping, from a different station.

It seems like my TV doesn't like the plugin?

R
Regards,
Richard.....

**Comment by o-lukas** [comment]
This sounds really strange. 

Have you tried removing the IP address from the config so the SmartThings API is used for checking the alive state?

The changes of the inputs are needed to check which applications are installed. If you don't need the applications you can simply disable this feature from the config. Maybe this even causes your TV to stop responding to the plugin.

**Comment by RichW02** [comment]
Sorry about the slow reply, I've been away with overseas visitors.

I have removed the IP from the problem TV and it is working, great!  I have noticed sometime after a restart of the bridge I need to leave it alone for quite  while and it eventually reflects the correct status of both TV.  

Thanks heaps and keep up the great work.  I'll look again for the donate link.

Regards,

Richard.....
