### ISSUE TITLE
Application list

### ISSUE THREAD

**Issue by edgeHB** [o-lukas/homebridge-smartthings-tv#326]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

Found an application list with even more IDs. Maybe you can integrate those IDs?

https://tavicu.github.io/homebridge-samsung-tizen/extra/applications.html#list-with-ids

Also: the application registering after a homebridge reboot does not work reliable for me. sometimes only the ids instead of the name is shown. (didn't report this, since it seems to be "work in progress".)

### Describe the solution you'd like

Integrate the IDs from above.

### Describe alternatives you've considered

none

### Additional context

none

**Comment by o-lukas** [comment]
I will have a look at it. I tried working with a larger list when initially developing the application feature but reduced the list shortly after because it takes a long time for checking the applications when the list is larger.
I think a config property would be the best so everyone can customize the list he/she wants to use.

I have also noticed the problem with disappearing names but I couldn't really confirm when the problem happens. Most of the time the problem solved itself after waiting for a few minutes...

**Comment by o-lukas** [comment]
Wow looks like I don't know my own plugin at this point...

I implemented custom application list a couple months ago in [v1.10.0](https://github.com/o-lukas/homebridge-smartthings-tv/releases/tag/v1.10.0). You can enter a custom list in the [device mappings](https://github.com/o-lukas/homebridge-smartthings-tv?tab=readme-ov-file#applications).
