### ISSUE TITLE
node 18 support?

### ISSUE THREAD

**Issue by bwp91** [o-lukas/homebridge-smartthings-tv#340]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through common issues
- [X] Updated plugin to the latest version (if applicable)

### Describe Your Problem

How come the decision to drop support for node 18?

**Comment by o-lukas** [comment]
I initially dropped it because semantic-release needed Node version 20.x. Because Builds were failing I simply dropped the support for Node version 18.x. 

I now do run semantic-release on the Node version 20.x build action and it is running again. 

So totally my fault because I didn't look close enough. Sorry for that - Node version 18.x is supported again in [v2.0.1](https://github.com/o-lukas/homebridge-smartthings-tv/releases/tag/v2.0.2).
